using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TripsTracker.Data.Migrations
{
    /// <inheritdoc />
    public partial class SeedAllCountries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Insert all ISO 3166-1 countries not already present (matched by IsoAlpha2).
            // Existing rows (IsHome, IsVisited flags) are preserved — only new rows are added.
            migrationBuilder.Sql(@"
INSERT INTO Countries (IsoNumeric, IsoAlpha2, Flag, Name, Region, IsHome, IsVisited, IsDeleted)
SELECT IsoNumeric, IsoAlpha2, Flag, Name, Region, 0, 0, 0
FROM (VALUES
    -- Africa
    (12,  N'DZ', N'🇩🇿', N'Algeria',                           N'Africa'),
    (24,  N'AO', N'🇦🇴', N'Angola',                            N'Africa'),
    (204, N'BJ', N'🇧🇯', N'Benin',                             N'Africa'),
    (72,  N'BW', N'🇧🇼', N'Botswana',                          N'Africa'),
    (854, N'BF', N'🇧🇫', N'Burkina Faso',                      N'Africa'),
    (108, N'BI', N'🇧🇮', N'Burundi',                           N'Africa'),
    (120, N'CM', N'🇨🇲', N'Cameroon',                          N'Africa'),
    (132, N'CV', N'🇨🇻', N'Cape Verde',                        N'Africa'),
    (140, N'CF', N'🇨🇫', N'Central African Republic',          N'Africa'),
    (148, N'TD', N'🇹🇩', N'Chad',                              N'Africa'),
    (174, N'KM', N'🇰🇲', N'Comoros',                           N'Africa'),
    (180, N'CD', N'🇨🇩', N'DR Congo',                          N'Africa'),
    (178, N'CG', N'🇨🇬', N'Congo',                             N'Africa'),
    (384, N'CI', N'🇨🇮', N'Côte d''Ivoire',                    N'Africa'),
    (262, N'DJ', N'🇩🇯', N'Djibouti',                          N'Africa'),
    (818, N'EG', N'🇪🇬', N'Egypt',                             N'Africa'),
    (226, N'GQ', N'🇬🇶', N'Equatorial Guinea',                 N'Africa'),
    (232, N'ER', N'🇪🇷', N'Eritrea',                           N'Africa'),
    (748, N'SZ', N'🇸🇿', N'Eswatini',                          N'Africa'),
    (231, N'ET', N'🇪🇹', N'Ethiopia',                          N'Africa'),
    (266, N'GA', N'🇬🇦', N'Gabon',                             N'Africa'),
    (270, N'GM', N'🇬🇲', N'Gambia',                            N'Africa'),
    (288, N'GH', N'🇬🇭', N'Ghana',                             N'Africa'),
    (324, N'GN', N'🇬🇳', N'Guinea',                            N'Africa'),
    (624, N'GW', N'🇬🇼', N'Guinea-Bissau',                     N'Africa'),
    (404, N'KE', N'🇰🇪', N'Kenya',                             N'Africa'),
    (426, N'LS', N'🇱🇸', N'Lesotho',                           N'Africa'),
    (430, N'LR', N'🇱🇷', N'Liberia',                           N'Africa'),
    (434, N'LY', N'🇱🇾', N'Libya',                             N'Africa'),
    (450, N'MG', N'🇲🇬', N'Madagascar',                        N'Africa'),
    (454, N'MW', N'🇲🇼', N'Malawi',                            N'Africa'),
    (466, N'ML', N'🇲🇱', N'Mali',                              N'Africa'),
    (478, N'MR', N'🇲🇷', N'Mauritania',                        N'Africa'),
    (480, N'MU', N'🇲🇺', N'Mauritius',                         N'Africa'),
    (504, N'MA', N'🇲🇦', N'Morocco',                           N'Africa'),
    (508, N'MZ', N'🇲🇿', N'Mozambique',                        N'Africa'),
    (516, N'NA', N'🇳🇦', N'Namibia',                           N'Africa'),
    (562, N'NE', N'🇳🇪', N'Niger',                             N'Africa'),
    (566, N'NG', N'🇳🇬', N'Nigeria',                           N'Africa'),
    (646, N'RW', N'🇷🇼', N'Rwanda',                            N'Africa'),
    (678, N'ST', N'🇸🇹', N'São Tomé and Príncipe',             N'Africa'),
    (686, N'SN', N'🇸🇳', N'Senegal',                           N'Africa'),
    (690, N'SC', N'🇸🇨', N'Seychelles',                        N'Africa'),
    (694, N'SL', N'🇸🇱', N'Sierra Leone',                      N'Africa'),
    (706, N'SO', N'🇸🇴', N'Somalia',                           N'Africa'),
    (710, N'ZA', N'🇿🇦', N'South Africa',                      N'Africa'),
    (728, N'SS', N'🇸🇸', N'South Sudan',                       N'Africa'),
    (729, N'SD', N'🇸🇩', N'Sudan',                             N'Africa'),
    (834, N'TZ', N'🇹🇿', N'Tanzania',                          N'Africa'),
    (768, N'TG', N'🇹🇬', N'Togo',                              N'Africa'),
    (788, N'TN', N'🇹🇳', N'Tunisia',                           N'Africa'),
    (800, N'UG', N'🇺🇬', N'Uganda',                            N'Africa'),
    (894, N'ZM', N'🇿🇲', N'Zambia',                            N'Africa'),
    (716, N'ZW', N'🇿🇼', N'Zimbabwe',                          N'Africa'),
    -- Americas
    (28,  N'AG', N'🇦🇬', N'Antigua and Barbuda',               N'Americas'),
    (32,  N'AR', N'🇦🇷', N'Argentina',                         N'Americas'),
    (44,  N'BS', N'🇧🇸', N'Bahamas',                           N'Americas'),
    (52,  N'BB', N'🇧🇧', N'Barbados',                          N'Americas'),
    (84,  N'BZ', N'🇧🇿', N'Belize',                            N'Americas'),
    (68,  N'BO', N'🇧🇴', N'Bolivia',                           N'Americas'),
    (76,  N'BR', N'🇧🇷', N'Brazil',                            N'Americas'),
    (124, N'CA', N'🇨🇦', N'Canada',                            N'Americas'),
    (152, N'CL', N'🇨🇱', N'Chile',                             N'Americas'),
    (170, N'CO', N'🇨🇴', N'Colombia',                          N'Americas'),
    (188, N'CR', N'🇨🇷', N'Costa Rica',                        N'Americas'),
    (192, N'CU', N'🇨🇺', N'Cuba',                              N'Americas'),
    (212, N'DM', N'🇩🇲', N'Dominica',                          N'Americas'),
    (214, N'DO', N'🇩🇴', N'Dominican Republic',                N'Americas'),
    (218, N'EC', N'🇪🇨', N'Ecuador',                           N'Americas'),
    (222, N'SV', N'🇸🇻', N'El Salvador',                       N'Americas'),
    (308, N'GD', N'🇬🇩', N'Grenada',                           N'Americas'),
    (320, N'GT', N'🇬🇹', N'Guatemala',                         N'Americas'),
    (328, N'GY', N'🇬🇾', N'Guyana',                            N'Americas'),
    (332, N'HT', N'🇭🇹', N'Haiti',                             N'Americas'),
    (340, N'HN', N'🇭🇳', N'Honduras',                          N'Americas'),
    (388, N'JM', N'🇯🇲', N'Jamaica',                           N'Americas'),
    (484, N'MX', N'🇲🇽', N'Mexico',                            N'Americas'),
    (558, N'NI', N'🇳🇮', N'Nicaragua',                         N'Americas'),
    (591, N'PA', N'🇵🇦', N'Panama',                            N'Americas'),
    (600, N'PY', N'🇵🇾', N'Paraguay',                          N'Americas'),
    (604, N'PE', N'🇵🇪', N'Peru',                              N'Americas'),
    (659, N'KN', N'🇰🇳', N'Saint Kitts and Nevis',             N'Americas'),
    (662, N'LC', N'🇱🇨', N'Saint Lucia',                       N'Americas'),
    (670, N'VC', N'🇻🇨', N'Saint Vincent and the Grenadines',  N'Americas'),
    (740, N'SR', N'🇸🇷', N'Suriname',                          N'Americas'),
    (780, N'TT', N'🇹🇹', N'Trinidad and Tobago',               N'Americas'),
    (840, N'US', N'🇺🇸', N'United States',                     N'Americas'),
    (858, N'UY', N'🇺🇾', N'Uruguay',                           N'Americas'),
    (862, N'VE', N'🇻🇪', N'Venezuela',                         N'Americas'),
    -- Asia
    (4,   N'AF', N'🇦🇫', N'Afghanistan',                       N'Asia'),
    (51,  N'AM', N'🇦🇲', N'Armenia',                           N'Asia'),
    (31,  N'AZ', N'🇦🇿', N'Azerbaijan',                        N'Asia'),
    (48,  N'BH', N'🇧🇭', N'Bahrain',                           N'Asia'),
    (50,  N'BD', N'🇧🇩', N'Bangladesh',                        N'Asia'),
    (64,  N'BT', N'🇧🇹', N'Bhutan',                            N'Asia'),
    (96,  N'BN', N'🇧🇳', N'Brunei',                            N'Asia'),
    (116, N'KH', N'🇰🇭', N'Cambodia',                          N'Asia'),
    (156, N'CN', N'🇨🇳', N'China',                             N'Asia'),
    (196, N'CY', N'🇨🇾', N'Cyprus',                            N'Asia'),
    (268, N'GE', N'🇬🇪', N'Georgia',                           N'Asia'),
    (356, N'IN', N'🇮🇳', N'India',                             N'Asia'),
    (360, N'ID', N'🇮🇩', N'Indonesia',                         N'Asia'),
    (364, N'IR', N'🇮🇷', N'Iran',                              N'Asia'),
    (368, N'IQ', N'🇮🇶', N'Iraq',                              N'Asia'),
    (376, N'IL', N'🇮🇱', N'Israel',                            N'Asia'),
    (392, N'JP', N'🇯🇵', N'Japan',                             N'Asia'),
    (400, N'JO', N'🇯🇴', N'Jordan',                            N'Asia'),
    (398, N'KZ', N'🇰🇿', N'Kazakhstan',                        N'Asia'),
    (414, N'KW', N'🇰🇼', N'Kuwait',                            N'Asia'),
    (417, N'KG', N'🇰🇬', N'Kyrgyzstan',                        N'Asia'),
    (418, N'LA', N'🇱🇦', N'Laos',                              N'Asia'),
    (422, N'LB', N'🇱🇧', N'Lebanon',                           N'Asia'),
    (458, N'MY', N'🇲🇾', N'Malaysia',                          N'Asia'),
    (462, N'MV', N'🇲🇻', N'Maldives',                          N'Asia'),
    (496, N'MN', N'🇲🇳', N'Mongolia',                          N'Asia'),
    (104, N'MM', N'🇲🇲', N'Myanmar',                           N'Asia'),
    (524, N'NP', N'🇳🇵', N'Nepal',                             N'Asia'),
    (408, N'KP', N'🇰🇵', N'North Korea',                       N'Asia'),
    (512, N'OM', N'🇴🇲', N'Oman',                              N'Asia'),
    (586, N'PK', N'🇵🇰', N'Pakistan',                          N'Asia'),
    (275, N'PS', N'🇵🇸', N'Palestine',                         N'Asia'),
    (608, N'PH', N'🇵🇭', N'Philippines',                       N'Asia'),
    (634, N'QA', N'🇶🇦', N'Qatar',                             N'Asia'),
    (682, N'SA', N'🇸🇦', N'Saudi Arabia',                      N'Asia'),
    (702, N'SG', N'🇸🇬', N'Singapore',                         N'Asia'),
    (410, N'KR', N'🇰🇷', N'South Korea',                       N'Asia'),
    (144, N'LK', N'🇱🇰', N'Sri Lanka',                         N'Asia'),
    (760, N'SY', N'🇸🇾', N'Syria',                             N'Asia'),
    (158, N'TW', N'🇹🇼', N'Taiwan',                            N'Asia'),
    (762, N'TJ', N'🇹🇯', N'Tajikistan',                        N'Asia'),
    (764, N'TH', N'🇹🇭', N'Thailand',                          N'Asia'),
    (626, N'TL', N'🇹🇱', N'Timor-Leste',                       N'Asia'),
    (795, N'TM', N'🇹🇲', N'Turkmenistan',                      N'Asia'),
    (784, N'AE', N'🇦🇪', N'United Arab Emirates',              N'Asia'),
    (860, N'UZ', N'🇺🇿', N'Uzbekistan',                        N'Asia'),
    (704, N'VN', N'🇻🇳', N'Vietnam',                           N'Asia'),
    (887, N'YE', N'🇾🇪', N'Yemen',                             N'Asia'),
    -- Europe
    (8,   N'AL', N'🇦🇱', N'Albania',                           N'Europe'),
    (20,  N'AD', N'🇦🇩', N'Andorra',                           N'Europe'),
    (40,  N'AT', N'🇦🇹', N'Austria',                           N'Europe'),
    (112, N'BY', N'🇧🇾', N'Belarus',                           N'Europe'),
    (56,  N'BE', N'🇧🇪', N'Belgium',                           N'Europe'),
    (70,  N'BA', N'🇧🇦', N'Bosnia and Herzegovina',            N'Europe'),
    (100, N'BG', N'🇧🇬', N'Bulgaria',                          N'Europe'),
    (191, N'HR', N'🇭🇷', N'Croatia',                           N'Europe'),
    (203, N'CZ', N'🇨🇿', N'Czechia',                           N'Europe'),
    (208, N'DK', N'🇩🇰', N'Denmark',                           N'Europe'),
    (233, N'EE', N'🇪🇪', N'Estonia',                           N'Europe'),
    (246, N'FI', N'🇫🇮', N'Finland',                           N'Europe'),
    (250, N'FR', N'🇫🇷', N'France',                            N'Europe'),
    (276, N'DE', N'🇩🇪', N'Germany',                           N'Europe'),
    (300, N'GR', N'🇬🇷', N'Greece',                            N'Europe'),
    (348, N'HU', N'🇭🇺', N'Hungary',                           N'Europe'),
    (352, N'IS', N'🇮🇸', N'Iceland',                           N'Europe'),
    (372, N'IE', N'🇮🇪', N'Ireland',                           N'Europe'),
    (380, N'IT', N'🇮🇹', N'Italy',                             N'Europe'),
    (383, N'XK', N'🇽🇰', N'Kosovo',                            N'Europe'),
    (428, N'LV', N'🇱🇻', N'Latvia',                            N'Europe'),
    (438, N'LI', N'🇱🇮', N'Liechtenstein',                     N'Europe'),
    (440, N'LT', N'🇱🇹', N'Lithuania',                         N'Europe'),
    (442, N'LU', N'🇱🇺', N'Luxembourg',                        N'Europe'),
    (470, N'MT', N'🇲🇹', N'Malta',                             N'Europe'),
    (498, N'MD', N'🇲🇩', N'Moldova',                           N'Europe'),
    (492, N'MC', N'🇲🇨', N'Monaco',                            N'Europe'),
    (499, N'ME', N'🇲🇪', N'Montenegro',                        N'Europe'),
    (528, N'NL', N'🇳🇱', N'Netherlands',                       N'Europe'),
    (807, N'MK', N'🇲🇰', N'North Macedonia',                   N'Europe'),
    (578, N'NO', N'🇳🇴', N'Norway',                            N'Europe'),
    (616, N'PL', N'🇵🇱', N'Poland',                            N'Europe'),
    (620, N'PT', N'🇵🇹', N'Portugal',                          N'Europe'),
    (642, N'RO', N'🇷🇴', N'Romania',                           N'Europe'),
    (643, N'RU', N'🇷🇺', N'Russia',                            N'Europe'),
    (674, N'SM', N'🇸🇲', N'San Marino',                        N'Europe'),
    (688, N'RS', N'🇷🇸', N'Serbia',                            N'Europe'),
    (703, N'SK', N'🇸🇰', N'Slovakia',                          N'Europe'),
    (705, N'SI', N'🇸🇮', N'Slovenia',                          N'Europe'),
    (724, N'ES', N'🇪🇸', N'Spain',                             N'Europe'),
    (752, N'SE', N'🇸🇪', N'Sweden',                            N'Europe'),
    (756, N'CH', N'🇨🇭', N'Switzerland',                       N'Europe'),
    (792, N'TR', N'🇹🇷', N'Türkiye',                           N'Europe'),
    (804, N'UA', N'🇺🇦', N'Ukraine',                           N'Europe'),
    (826, N'GB', N'🇬🇧', N'United Kingdom',                    N'Europe'),
    (336, N'VA', N'🇻🇦', N'Vatican City',                      N'Europe'),
    -- Oceania
    (36,  N'AU', N'🇦🇺', N'Australia',                         N'Oceania'),
    (242, N'FJ', N'🇫🇯', N'Fiji',                              N'Oceania'),
    (296, N'KI', N'🇰🇮', N'Kiribati',                          N'Oceania'),
    (584, N'MH', N'🇲🇭', N'Marshall Islands',                  N'Oceania'),
    (583, N'FM', N'🇫🇲', N'Micronesia',                        N'Oceania'),
    (520, N'NR', N'🇳🇷', N'Nauru',                             N'Oceania'),
    (554, N'NZ', N'🇳🇿', N'New Zealand',                       N'Oceania'),
    (585, N'PW', N'🇵🇼', N'Palau',                             N'Oceania'),
    (598, N'PG', N'🇵🇬', N'Papua New Guinea',                  N'Oceania'),
    (882, N'WS', N'🇼🇸', N'Samoa',                             N'Oceania'),
    (90,  N'SB', N'🇸🇧', N'Solomon Islands',                   N'Oceania'),
    (776, N'TO', N'🇹🇴', N'Tonga',                             N'Oceania'),
    (798, N'TV', N'🇹🇻', N'Tuvalu',                            N'Oceania'),
    (548, N'VU', N'🇻🇺', N'Vanuatu',                           N'Oceania')
) AS v(IsoNumeric, IsoAlpha2, Flag, Name, Region)
WHERE NOT EXISTS (SELECT 1 FROM Countries c WHERE c.IsoAlpha2 = v.IsoAlpha2)
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove countries that were added by this migration (IsHome=0, IsVisited=0 only —
            // any row a user has marked as visited/home is kept to preserve user data).
            migrationBuilder.Sql(@"
DELETE FROM Countries
WHERE IsHome = 0 AND IsVisited = 0 AND IsDeleted = 0
  AND IsoAlpha2 IN (
    'DZ','AO','BJ','BW','BF','BI','CM','CV','CF','TD','KM','CD','CG','CI','DJ',
    'EG','GQ','ER','SZ','ET','GA','GM','GH','GN','GW','KE','LS','LR','LY','MG',
    'MW','ML','MR','MU','MA','MZ','NA','NE','NG','RW','ST','SN','SC','SL','SO',
    'ZA','SS','SD','TZ','TG','TN','UG','ZM','ZW',
    'AG','BS','BB','BZ','BO','DM','DO','EC','SV','GD','GT','GY','HT','HN','JM',
    'NI','PY','KN','LC','VC','SR','TT','UY','VE',
    'AF','AM','AZ','BH','BD','BT','BN','KH','CY','GE','IR','IQ','IL','JO','KZ',
    'KW','KG','LA','LB','MV','MN','MM','NP','KP','OM','PK','PS','QA','SY','TW',
    'TJ','TL','TM','UZ','YE',
    'AL','AD','BY','BA','BG','HR','CZ','EE','XK','LV','LI','LT','LU','MT','MD',
    'MC','ME','MK','SM','RS','SK','SI','VA',
    'FJ','KI','MH','FM','NR','PW','PG','WS','SB','TO','TV','VU'
  )
");
        }
    }
}
