using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TripsTracker.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddIsoAlpha3ToCountries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "IsoAlpha3",
                table: "Countries",
                type: "nvarchar(3)",
                maxLength: 3,
                nullable: true);

            // Seed ISO Alpha-3 codes for all countries
            migrationBuilder.Sql(@"
UPDATE Countries SET IsoAlpha3 = CASE IsoAlpha2
  WHEN 'AD' THEN 'AND' WHEN 'AE' THEN 'ARE' WHEN 'AF' THEN 'AFG' WHEN 'AG' THEN 'ATG'
  WHEN 'AL' THEN 'ALB' WHEN 'AM' THEN 'ARM' WHEN 'AO' THEN 'AGO' WHEN 'AQ' THEN 'ATA'
  WHEN 'AR' THEN 'ARG' WHEN 'AT' THEN 'AUT' WHEN 'AU' THEN 'AUS' WHEN 'AZ' THEN 'AZE'
  WHEN 'BA' THEN 'BIH' WHEN 'BB' THEN 'BRB' WHEN 'BD' THEN 'BGD' WHEN 'BE' THEN 'BEL'
  WHEN 'BF' THEN 'BFA' WHEN 'BG' THEN 'BGR' WHEN 'BH' THEN 'BHR' WHEN 'BI' THEN 'BDI'
  WHEN 'BJ' THEN 'BEN' WHEN 'BN' THEN 'BRN' WHEN 'BO' THEN 'BOL' WHEN 'BR' THEN 'BRA'
  WHEN 'BS' THEN 'BHS' WHEN 'BT' THEN 'BTN' WHEN 'BW' THEN 'BWA' WHEN 'BY' THEN 'BLR'
  WHEN 'BZ' THEN 'BLZ' WHEN 'CA' THEN 'CAN' WHEN 'CD' THEN 'COD' WHEN 'CF' THEN 'CAF'
  WHEN 'CG' THEN 'COG' WHEN 'CH' THEN 'CHE' WHEN 'CI' THEN 'CIV' WHEN 'CK' THEN 'COK'
  WHEN 'CL' THEN 'CHL' WHEN 'CM' THEN 'CMR' WHEN 'CN' THEN 'CHN' WHEN 'CO' THEN 'COL'
  WHEN 'CR' THEN 'CRI' WHEN 'CU' THEN 'CUB' WHEN 'CV' THEN 'CPV' WHEN 'CY' THEN 'CYP'
  WHEN 'CZ' THEN 'CZE' WHEN 'DE' THEN 'DEU' WHEN 'DJ' THEN 'DJI' WHEN 'DK' THEN 'DNK'
  WHEN 'DM' THEN 'DMA' WHEN 'DO' THEN 'DOM' WHEN 'DZ' THEN 'DZA' WHEN 'EC' THEN 'ECU'
  WHEN 'EE' THEN 'EST' WHEN 'EG' THEN 'EGY' WHEN 'EH' THEN 'ESH' WHEN 'ER' THEN 'ERI'
  WHEN 'ES' THEN 'ESP' WHEN 'ET' THEN 'ETH' WHEN 'FI' THEN 'FIN' WHEN 'FJ' THEN 'FJI'
  WHEN 'FK' THEN 'FLK' WHEN 'FM' THEN 'FSM' WHEN 'FR' THEN 'FRA' WHEN 'GA' THEN 'GAB'
  WHEN 'GB' THEN 'GBR' WHEN 'GD' THEN 'GRD' WHEN 'GE' THEN 'GEO' WHEN 'GH' THEN 'GHA'
  WHEN 'GM' THEN 'GMB' WHEN 'GN' THEN 'GIN' WHEN 'GQ' THEN 'GNQ' WHEN 'GR' THEN 'GRC'
  WHEN 'GT' THEN 'GTM' WHEN 'GW' THEN 'GNB' WHEN 'GY' THEN 'GUY' WHEN 'HK' THEN 'HKG'
  WHEN 'HN' THEN 'HND' WHEN 'HR' THEN 'HRV' WHEN 'HT' THEN 'HTI' WHEN 'HU' THEN 'HUN'
  WHEN 'ID' THEN 'IDN' WHEN 'IE' THEN 'IRL' WHEN 'IL' THEN 'ISR' WHEN 'IN' THEN 'IND'
  WHEN 'IQ' THEN 'IRQ' WHEN 'IR' THEN 'IRN' WHEN 'IS' THEN 'ISL' WHEN 'IT' THEN 'ITA'
  WHEN 'JM' THEN 'JAM' WHEN 'JO' THEN 'JOR' WHEN 'JP' THEN 'JPN' WHEN 'KE' THEN 'KEN'
  WHEN 'KG' THEN 'KGZ' WHEN 'KH' THEN 'KHM' WHEN 'KI' THEN 'KIR' WHEN 'KM' THEN 'COM'
  WHEN 'KN' THEN 'KNA' WHEN 'KP' THEN 'PRK' WHEN 'KR' THEN 'KOR' WHEN 'KW' THEN 'KWT'
  WHEN 'KZ' THEN 'KAZ' WHEN 'LA' THEN 'LAO' WHEN 'LB' THEN 'LBN' WHEN 'LC' THEN 'LCA'
  WHEN 'LI' THEN 'LIE' WHEN 'LK' THEN 'LKA' WHEN 'LR' THEN 'LBR' WHEN 'LS' THEN 'LSO'
  WHEN 'LT' THEN 'LTU' WHEN 'LU' THEN 'LUX' WHEN 'LV' THEN 'LVA' WHEN 'LY' THEN 'LBY'
  WHEN 'MA' THEN 'MAR' WHEN 'MC' THEN 'MCO' WHEN 'MD' THEN 'MDA' WHEN 'ME' THEN 'MNE'
  WHEN 'MG' THEN 'MDG' WHEN 'MH' THEN 'MHL' WHEN 'MK' THEN 'MKD' WHEN 'ML' THEN 'MLI'
  WHEN 'MM' THEN 'MMR' WHEN 'MN' THEN 'MNG' WHEN 'MO' THEN 'MAC' WHEN 'MR' THEN 'MRT'
  WHEN 'MT' THEN 'MLT' WHEN 'MU' THEN 'MUS' WHEN 'MV' THEN 'MDV' WHEN 'MW' THEN 'MWI'
  WHEN 'MX' THEN 'MEX' WHEN 'MY' THEN 'MYS' WHEN 'MZ' THEN 'MOZ' WHEN 'NA' THEN 'NAM'
  WHEN 'NE' THEN 'NER' WHEN 'NG' THEN 'NGA' WHEN 'NI' THEN 'NIC' WHEN 'NL' THEN 'NLD'
  WHEN 'NO' THEN 'NOR' WHEN 'NP' THEN 'NPL' WHEN 'NR' THEN 'NRU' WHEN 'NU' THEN 'NIU'
  WHEN 'NZ' THEN 'NZL' WHEN 'OM' THEN 'OMN' WHEN 'PA' THEN 'PAN' WHEN 'PE' THEN 'PER'
  WHEN 'PG' THEN 'PNG' WHEN 'PH' THEN 'PHL' WHEN 'PK' THEN 'PAK' WHEN 'PL' THEN 'POL'
  WHEN 'PS' THEN 'PSE' WHEN 'PT' THEN 'PRT' WHEN 'PW' THEN 'PLW' WHEN 'PY' THEN 'PRY'
  WHEN 'QA' THEN 'QAT' WHEN 'RO' THEN 'ROU' WHEN 'RS' THEN 'SRB' WHEN 'RU' THEN 'RUS'
  WHEN 'RW' THEN 'RWA' WHEN 'SA' THEN 'SAU' WHEN 'SB' THEN 'SLB' WHEN 'SC' THEN 'SYC'
  WHEN 'SD' THEN 'SDN' WHEN 'SE' THEN 'SWE' WHEN 'SG' THEN 'SGP' WHEN 'SI' THEN 'SVN'
  WHEN 'SK' THEN 'SVK' WHEN 'SL' THEN 'SLE' WHEN 'SM' THEN 'SMR' WHEN 'SN' THEN 'SEN'
  WHEN 'SO' THEN 'SOM' WHEN 'SR' THEN 'SUR' WHEN 'SS' THEN 'SSD' WHEN 'ST' THEN 'STP'
  WHEN 'SV' THEN 'SLV' WHEN 'SY' THEN 'SYR' WHEN 'SZ' THEN 'SWZ' WHEN 'TD' THEN 'TCD'
  WHEN 'TG' THEN 'TGO' WHEN 'TH' THEN 'THA' WHEN 'TJ' THEN 'TJK' WHEN 'TL' THEN 'TLS'
  WHEN 'TM' THEN 'TKM' WHEN 'TN' THEN 'TUN' WHEN 'TO' THEN 'TON' WHEN 'TR' THEN 'TUR'
  WHEN 'TT' THEN 'TTO' WHEN 'TV' THEN 'TUV' WHEN 'TW' THEN 'TWN' WHEN 'TZ' THEN 'TZA'
  WHEN 'UA' THEN 'UKR' WHEN 'UG' THEN 'UGA' WHEN 'US' THEN 'USA' WHEN 'UY' THEN 'URY'
  WHEN 'UZ' THEN 'UZB' WHEN 'VA' THEN 'VAT' WHEN 'VC' THEN 'VCT' WHEN 'VE' THEN 'VEN'
  WHEN 'VN' THEN 'VNM' WHEN 'VU' THEN 'VUT' WHEN 'WS' THEN 'WSM' WHEN 'XK' THEN 'XKX'
  WHEN 'YE' THEN 'YEM' WHEN 'ZA' THEN 'ZAF' WHEN 'ZM' THEN 'ZMB' WHEN 'ZW' THEN 'ZWE'
  ELSE NULL
END;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsoAlpha3",
                table: "Countries");
        }
    }
}
